/*
   This file has been generated by IDA.
   It contains local type definitions from
   the type library 'ntkrnlmp.exe'
*/

#define __int8 char
#define __int16 short
#define __int32 int
#define __int64 long long

/* 23 */
typedef struct
{
  unsigned __int16 Machine;
  unsigned __int16 NumberOfSections;
  unsigned int TimeDateStamp;
  unsigned int PointerToSymbolTable;
  unsigned int NumberOfSymbols;
  unsigned __int16 SizeOfOptionalHeader;
  unsigned __int16 Characteristics;
} _IMAGE_FILE_HEADER;

typedef struct
{
  unsigned int VirtualAddress;
  unsigned int Size;
} _IMAGE_DATA_DIRECTORY;

typedef struct
{
  unsigned __int16 Magic;
  char MajorLinkerVersion;
  char MinorLinkerVersion;
  unsigned int SizeOfCode;
  unsigned int SizeOfInitializedData;
  unsigned int SizeOfUninitializedData;
  unsigned int AddressOfEntryPoint;
  unsigned int BaseOfCode;
  unsigned int BaseOfData;
  unsigned int ImageBase;
  unsigned int SectionAlignment;
  unsigned int FileAlignment;
  unsigned __int16 MajorOperatingSystemVersion;
  unsigned __int16 MinorOperatingSystemVersion;
  unsigned __int16 MajorImageVersion;
  unsigned __int16 MinorImageVersion;
  unsigned __int16 MajorSubsystemVersion;
  unsigned __int16 MinorSubsystemVersion;
  unsigned int Win32VersionValue;
  unsigned int SizeOfImage;
  unsigned int SizeOfHeaders;
  unsigned int CheckSum;
  unsigned __int16 Subsystem;
  unsigned __int16 DllCharacteristics;
  unsigned int SizeOfStackReserve;
  unsigned int SizeOfStackCommit;
  unsigned int SizeOfHeapReserve;
  unsigned int SizeOfHeapCommit;
  unsigned int LoaderFlags;
  unsigned int NumberOfRvaAndSizes;
  _IMAGE_DATA_DIRECTORY DataDirectory[16];
} _IMAGE_OPTIONAL_HEADER;

/* 26 */
typedef struct
{
  unsigned int Signature;
  _IMAGE_FILE_HEADER FileHeader;
  _IMAGE_OPTIONAL_HEADER OptionalHeader;
} _IMAGE_NT_HEADERS;

/* 900 */
typedef struct
{
  __int16 magic;
  __int16 cblp;
  __int16 cp;
  __int16 crlc;
  __int16 cparhdr;
  __int16 minalloc;
  __int16 maxalloc;
  __int16 e_ss;
  __int16 e_sp;
  __int16 csum;
  __int16 e_ip;
  __int16 e_cs;
  __int16 lfarlc;
  __int16 ovno;
  __int16 res[4];
  __int16 oemid;
  __int16 oeminfo;
  __int16 res2[10];
  int e_lfanew;
} DOSHeader;

/* 901 */
typedef struct
{
  __int16 Machine;
  __int16 NumberOfSections;
  int TimeDateStamp;
  int PointerToSymbolTable;
  int NumberOfSymbols;
  __int16 SizeOfOptionalHeader;
  __int16 Characteristics;
} PEHeader;

/* 903 */
typedef struct
{
  int Signature;
  _IMAGE_FILE_HEADER peHeader;
  _IMAGE_OPTIONAL_HEADER optHeader;
} ProgramHeader;

typedef struct
{
  char Name[8];
  unsigned int VirtualSize;
  unsigned int VirtualAddress;
  unsigned int SizeOfRawData;
  unsigned int PointerToRawData;
  unsigned int PointerToRelocations;
  unsigned int PointerToLinenumbers;
  unsigned __int16 NumberOfRelocations;
  unsigned __int16 NumberOfLinenumbers;
  unsigned int Characteristics;
} _IMAGE_SECTION_HEADER;
